### ISSUE TITLE
crash on high flip

### ISSUE THREAD

**Issue by jkevo** [eQueline/Megiston-Incremental#1]
any flip over about e5700 upside down triangles crashes web page.

**Comment by jkevo** [comment]
I think it might be an infinite loop because the web page freezes and will not respond

**Comment by etrotta** [comment]
A bit of additional information:
I was testing this a bit and I believe that the issue may be caused by the game trying to divide your Resource by Zero when you purchase Triangles after Flipping, when you reach 1e12 total flips.

**Comment by eQueline** [comment]
Thanks for the note, i will investigate. This amount of flipped triangles is currently beyond balanced end-game, so i haven't tested those cases
